### ISSUE TITLE
Challenge Closed error with passive key

### ISSUE THREAD

**Issue by PBurdelak** [hCaptcha/hcaptcha-android-sdk#131]
While reviewing the error logs of the app, I noticed that sometimes users run into the "Challenge Closed" error. From what I understand this error should appear when a user has closed a challenge. But the SiteKey is set to 100% passive, so the user should not encounter the challenge. I was able to reproduce this error few times, but the challenge did not even show up, as the error suggests.

VERSION: 3.9.1

```
val config = HCaptchaConfig.builder()
    .siteKey(siteKey)
    .size(HCaptchaSize.INVISIBLE)
    .loading(false)
    .build()
HCaptcha.getClient(activity)
    .setup(config)
    .verifyWithHCaptcha()
    .addOnSuccessListener { hCaptchaTokenResponse ->
        onReady(hCaptchaTokenResponse.tokenResult)
        hCaptchaTokenResponse.markUsed()
    }
    .addOnFailureListener { exception ->
        recordException(exception)
        onReady(null)
    }
```

The error occurs in two variants:

90%
```
Non-fatal Exception: com.hcaptcha.sdk.f: Challenge Closed
       at com.hcaptcha.sdk.HCaptchaJSInterface.lambda$onError$1(SourceFile:5)
       at android.os.Handler.handleCallback(Handler.java:899)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:238)
       at android.app.ActivityThread.main(ActivityThread.java:7864)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:998)
```

10%
```
Non-fatal Exception: com.hcaptcha.sdk.f: Challenge Closed
       at com.hcaptcha.sdk.HCaptchaDialogFragment.onCancel(SourceFile:13)
       at androidx.fragment.app.DialogFragment$2.onCancel(DialogFragment.java:122)
       at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1913)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by CAMOBAP** [comment]
@PBurdelak thanks for the contact

Even if the key is 100% passive, on Android, Users are able to press back button which will lead to hCaptcha close and "Challenge Close" error will be emitted.

This behavior can be changed with `.hideDialog(true)` in `HCaptchaConfig.builder()`. And this will mean that sdk will not handle back button anymore, and you will have to handle it in the app code

Please let me know if you have any questions/proposals

**Comment by PBurdelak** [comment]
@CAMOBAP thanks for your reply

Previously, we had this option enabled, and there were messages that sometimes there was also a problem with it (however, I do not have logs from that time). I think we can try with this and just watch the logs for now.

This option was disabled because our team wants to gradually reduce the passive level of the key (e.g. 99%, 95% passive).
Is there anything else we can do without turning on the `hideDialog` option?

**Comment by CAMOBAP** [comment]
@PBurdelak thanks for reply

As I noted above, according to my investigation, the reason why this issue is happens is interruption from user side.

Probably we can provide additional option (in `HCaptchaConfig.builder`) that will prevent this behavior (i.e. user back presses will be ignored) but this will affect UX

Will it works for you?

> Is there anything else we can do without turning on the hideDialog option?

To me it looks like for this particular error it can be gracefully handled with asking a user to do verification again

**Comment by CAMOBAP** [comment]
@PBurdelak after in-team discussion we found that there is another solution that is exists, is to use `retryPredicate` like this:

```java
val config = HCaptchaConfig.builder()
    .siteKey(siteKey)
    .size(HCaptchaSize.INVISIBLE)
    .loading(false)
    .retryPredicate((config, exception) -> exception.getHCaptchaError() == HCaptchaError.CHALLENGE_CLOSED)
    .build()
```

This will make SDK to ignore Back button presses

**Comment by CAMOBAP** [comment]
@PBurdelak feel free to reopen the ticket if you still have questions
