### ISSUE TITLE
Crash on android <= 7.2

### ISSUE THREAD

**Issue by MrNektom** [hCaptcha/hcaptcha-android-sdk#145]

**Comment by MrNektom** [comment]
Crash with this exception
```
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/BootstrapMethodError;
at com.fasterxml.jackson.databind.util.ExceptionUtil.isFatal(ExceptionUtil.java:51)
at com.fasterxml.jackson.databind.util.ExceptionUtil.rethrowIfFatal(ExceptionUtil.java:31)
at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.<clinit>(JacksonAnnotationIntrospector.java:70)
at com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:400)
at com.hcaptcha.sdk.HCaptchaJSInterface.<init>(SourceFile)
at com.hcaptcha.sdk.HCaptchaWebViewHelper.setupWebView(SourceFile)
at com.hcaptcha.sdk.HCaptchaWebViewHelper.<init>(SourceFile)
at com.hcaptcha.sdk.HCaptchaDialogFragment.onCreateView(SourceFile)
at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3114)
at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:775)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:557)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)                                                                                                    	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3042)                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2952)                                                                                                    	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)                                                                                                    	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350)                                                                                                    	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
at android.app.Activity.performStart(Activity.java:6679)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2609)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6077)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.lang.BootstrapMethodError" on path: DexPathList[[zip file "/data/app/ru.kencomics.manga.debug-1/base.apk"],nativeLibraryDirectories=[/data/app/ru.kencomics.manga.debug-1/lib/x86, /data/app/ru.kencomics.manga.debug-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at com.fasterxml.jackson.databind.util.ExceptionUtil.isFatal(ExceptionUtil.java:51) 
at com.fasterxml.jackson.databind.util.ExceptionUtil.rethrowIfFatal(ExceptionUtil.java:31) 
at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.<clinit>(JacksonAnnotationIntrospector.java:70) 
at com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:400) 
at com.hcaptcha.sdk.HCaptchaJSInterface.<init>(SourceFile) 
at com.hcaptcha.sdk.HCaptchaWebViewHelper.setupWebView(SourceFile) 
at com.hcaptcha.sdk.HCaptchaWebViewHelper.<init>(SourceFile) 
at com.hcaptcha.sdk.HCaptchaDialogFragment.onCreateView(SourceFile) 
at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3114) 
at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:775) 
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:557) 
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272) 
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943) 
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845) 
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782) 
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3042) 
at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2952) 
at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263) 
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350) 
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248) 
at android.app.Activity.performStart(Activity.java:6679) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2609) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
at android.app.ActivityThread.-wrap12(ActivityThread.java) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:154) 
at android.app.ActivityThread.main(ActivityThread.java:6077) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
```

**Comment by e271828-** [comment]
@MrNektom any other info like device type, OS version, action taken, etc?

**Comment by MrNektom** [comment]
No, only on os version 7.1 and lower

**Comment by CAMOBAP** [comment]
Looks interesting:
- no obfuscation in the stack trace was detected
- the package name is `ru.kencomics.manga.debug-1`

So probably the issue reproduced under development

According to documentation, https://docs.oracle.com/javase/7/docs/api/java/lang/BootstrapMethodError.html was introduced in Java 1.7, so I assume that the JVM is probably 1.6

In general, the issue has nothing to do with hCaptcha SDK because it fails in 
third-party library https://github.com/FasterXML/jackson-databind/blob/2.17/src/main/java/com/fasterxml/jackson/databind/util/ExceptionUtil.java#L57

But to continue the investigation you can provide more information about the environment i.e. exact OS version and/or device model

As potential workaround, you can restrict `com.fasterxml.jackson.core:jackson-databind` to `2.0 - 2.7` [per the documentation it uses JDK 6](https://github.com/FasterXML/jackson-databind?tab=readme-ov-file#jdk), but there is no guarantee that there will be no issues in other places because hCaptcha SDK relies on Java 7
