### ISSUE TITLE
Crashes due to IllegalStateException

### ISSUE THREAD

**Issue by giangpham96** [hCaptcha/hcaptcha-android-sdk#60]
Here's the stacktrace
```
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1844)
       at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1884)
       at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:329)
       at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:294)
       at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:355)
       at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:307)
       at com.hcaptcha.sdk.HCaptchaDialogFragment.onFailure(SourceFile:42)
       at com.hcaptcha.sdk.HCaptchaJSInterface$2.run(SourceFile:13)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

Maybe the SDK should consider using `dismissAllowingStateLoss` instead of `dismiss`?

**Comment by e271828-** [comment]
@giangpham96 do you happen to have a repro?

**Comment by CAMOBAP** [comment]
In theory, this may happen on the back button which will hide the app + simultaneously click pressing outside the captcha (which will lead to the close error)

The proposed solution looks good because we are really should not care about state loss `onSucess` or `onFailure`
